### ISSUE TITLE
Documentation master task list

### ISSUE THREAD

**Issue by m-renaud** [haskell/containers#495]
- [x] Improve Data.Sequence module description
- [ ] Improve Data.Map (Lazy and Strict variants) module descriptions
- [ ] Improve Data.IntMap (Lazy and Strict variants) module descriptions
- [ ] Improve Data.Set module description
- [ ] Improve Data.IntSet module description
- [ ] Improve Data.Graph module description
- [ ] Improve Data.Tree module description
- [ ] Consistently format Haddock examples in expandable sections throughout package
- [ ] Gather consensus on Haddock format (#486) and use throughout package
- [ ] Add longer Set examples to bottom of [Set introduction](https://haskell-containers.readthedocs.io/en/latest/sets.html)
- [ ] Add longer Map examples to bottom of [Map introduction](https://haskell-containers.readthedocs.io/en/latest/maps.html)
- [ ] Add longer Sequence examples to bottom of [Sequence introduction](https://haskell-containers.readthedocs.io/en/latest/sequence.html)
- [ ] Add introduction for Data.Tree at https://haskell-containers.readthedocs.io
- [ ] Add examples to Data.Tree Haddocks 
- [ ] Add introduction for Data.Graph at https://haskell-containers.readthedocs.io
- [ ] Add examples to Data.Graph Haddocks

**Notes:**
- Module Haddock descriptions should:
  + link out to appropriate page at https://haskell-containers.readthedocs.io
  + follow the format of the [new Data.Sequence module description](http://www.m-renaud.com/haddocks/containers-0.5.10.2/Data-Sequence.html)
  + link to appropriate [performance benchmarks](https://github.com/haskell-perf)
